import type { MasterItemAliasDef, MasterItemDefinition } from "@/lib/masterItemCatalog/types";

function a(
  text: string,
  weight: number,
  t: MasterItemAliasDef["aliasType"] = "SYNONYM",
): MasterItemAliasDef {
  return { text, weight, aliasType: t };
}

/**
 * Base mestre global (hospitalidade) — espelhada na migração SQL `master_item_catalog`.
 * Usada em onboarding, sugestão e futura importação XML.
 */
export const MASTER_ITEM_DEFINITIONS: MasterItemDefinition[] = [
  {
    id: "mc-beb-cerveja-estilos",
    canonicalName: "Cerveja e estilos (revenda)",
    family: "Bebidas alcoólicas",
    subfamily: "Cervejas",
    conceptType: "BEBIDA_REVENDA",
    defaultUnit: "un",
    purchaseUnits: ["cx", "fardo", "barril", "lata"],
    baseConfidence: 0.9,
    recipeCandidate: false,
    neverRecipe: true,
    keywordsPositive: ["lata", "garrafa", "long neck", "473", "600", "355", "barril", "chope", "chopp", "keg", "30l", "50l"],
    keywordsNegative: [],
    aliases: [
      a("cerveja", 0.92),
      a("cerv", 0.88, "ABBREVIATION"),
      a("beer", 0.9, "SYNONYM"),
      a("chope", 0.9),
      a("chopp", 0.9),
      a("ipa", 0.93),
      a("apa", 0.93),
      a("pilsen", 0.94),
      a("pilsner", 0.94),
      a("lager", 0.92),
      a("stout", 0.91),
      a("weiss", 0.9),
      a("witbier", 0.9),
      a("hefeweizen", 0.9),
      a("pale ale", 0.91),
      a("session ipa", 0.92),
      a("neipa", 0.92),
    ],
  },
  {
    id: "mc-beb-destilados",
    canonicalName: "Destilados e licores (revenda)",
    family: "Bebidas alcoólicas",
    subfamily: "Destilados",
    conceptType: "BEBIDA_REVENDA",
    defaultUnit: "un",
    purchaseUnits: ["garrafa"],
    baseConfidence: 0.88,
    recipeCandidate: false,
    neverRecipe: true,
    keywordsPositive: ["750", "1000", "ml"],
    keywordsNegative: [],
    aliases: [
      a("vodka", 0.92),
      a("gin", 0.92),
      a("gim", 0.88, "ABBREVIATION"),
      a("rum", 0.9),
      a("tequila", 0.9),
      a("whisky", 0.9),
      a("whiskey", 0.9),
      a("cachaca", 0.88),
      a("cachaça", 0.88),
      a("licor", 0.88),
    ],
  },
  {
    id: "mc-beb-vinho-espumante",
    canonicalName: "Vinho e espumante (revenda)",
    family: "Bebidas alcoólicas",
    subfamily: "Vinhos e espumantes",
    conceptType: "BEBIDA_REVENDA",
    defaultUnit: "un",
    purchaseUnits: ["garrafa"],
    baseConfidence: 0.87,
    recipeCandidate: false,
    neverRecipe: true,
    keywordsPositive: [],
    keywordsNegative: [],
    aliases: [
      a("vinho", 0.91),
      a("espumante", 0.9),
      a("champagne", 0.88, "POPULAR_NAME"),
      a("prosecco", 0.86),
    ],
  },
  {
    id: "mc-beb-na",
    canonicalName: "Bebidas não alcoólicas (revenda)",
    family: "Bebidas não alcoólicas",
    subfamily: "Refrigerantes / sucos / águas",
    conceptType: "BEBIDA_REVENDA",
    defaultUnit: "un",
    purchaseUnits: ["cx", "fardo", "garrafa", "lata"],
    baseConfidence: 0.86,
    recipeCandidate: false,
    neverRecipe: true,
    keywordsPositive: ["lata", "pet", "600", "2l", "1l"],
    keywordsNegative: [],
    aliases: [
      a("refrigerante", 0.9),
      a("refri", 0.86, "ABBREVIATION"),
      a("coca", 0.85),
      a("guarana", 0.85),
      a("guaraná", 0.85),
      a("suco", 0.84),
      a("agua", 0.84),
      a("água", 0.84),
      a("energetico", 0.84),
      a("energético", 0.84),
      a("tonica", 0.82),
      a("tônica", 0.82),
      a("soda", 0.82),
      a("cha", 0.8),
      a("chá", 0.8),
      a("cafe", 0.8),
      a("café", 0.8),
    ],
  },
  {
    id: "mc-ins-horti-mercado",
    canonicalName: "Insumos hortifruti e mercearia seca",
    family: "Mercearia seca",
    subfamily: "Grãos / básicos",
    conceptType: "INSUMO",
    defaultUnit: "kg",
    purchaseUnits: ["kg", "g", "cx", "saco"],
    baseConfidence: 0.85,
    recipeCandidate: true,
    neverRecipe: false,
    keywordsPositive: ["kg", "10 kg", "5 kg", "saco"],
    keywordsNegative: [],
    aliases: [
      a("limao", 0.9),
      a("limão", 0.9),
      a("tahiti", 0.88),
      a("acucar", 0.88),
      a("açúcar", 0.88),
      a("sal", 0.85),
      a("farinha", 0.88),
      a("arroz", 0.88),
      a("feijao", 0.88),
      a("feijão", 0.88),
      a("oleo", 0.86),
      a("óleo", 0.86),
      a("azeite", 0.88),
      a("manteiga", 0.86),
      a("leite", 0.85),
      a("creme de leite", 0.87),
      a("molho", 0.82),
      a("tomate", 0.85),
      a("cebola", 0.85),
      a("alho", 0.86),
      a("hortela", 0.86),
      a("hortelã", 0.86),
      a("maracuja", 0.84),
      a("maracujá", 0.84),
      a("morango", 0.84),
      a("polpa", 0.86),
      a("xarope", 0.87),
      a("gelo", 0.84),
      a("pure", 0.85),
      a("purê", 0.85),
      a("calda", 0.84),
    ],
  },
  {
    id: "mc-ins-xarope-acucar",
    canonicalName: "Xarope de açúcar / calda simples",
    family: "Temperos e especiarias",
    subfamily: "Xaropes",
    conceptType: "INSUMO",
    defaultUnit: "l",
    purchaseUnits: ["gl", "frasco"],
    baseConfidence: 0.88,
    recipeCandidate: true,
    neverRecipe: false,
    keywordsPositive: [],
    keywordsNegative: [],
    aliases: [
      a("xarope de acucar", 0.92),
      a("xarope de açúcar", 0.92),
      a("xarope simples", 0.9),
    ],
  },
  {
    id: "mc-carnes-frios",
    canonicalName: "Carnes, frios e laticínios (insumo)",
    family: "Carnes",
    subfamily: "Frios e processados",
    conceptType: "INSUMO",
    defaultUnit: "kg",
    purchaseUnits: ["kg", "cx"],
    baseConfidence: 0.84,
    recipeCandidate: true,
    neverRecipe: false,
    keywordsPositive: [],
    keywordsNegative: [],
    aliases: [
      a("picanha", 0.86),
      a("file", 0.84),
      a("filé", 0.84),
      a("contra file", 0.84),
      a("frango", 0.86),
      a("peito de frango", 0.87),
      a("bacon", 0.85),
      a("calabresa", 0.85),
      a("presunto", 0.85),
      a("mucarela", 0.85),
      a("muçarela", 0.85),
      a("parmesao", 0.84),
      a("parmesão", 0.84),
      a("catupiry", 0.86),
      a("requeijao", 0.86),
      a("requeijão", 0.86),
    ],
  },
  {
    id: "mc-embal-limp",
    canonicalName: "Embalagens e descartáveis",
    family: "Embalagens",
    subfamily: "Uso único",
    conceptType: "ITEM_OPERACIONAL",
    defaultUnit: "un",
    purchaseUnits: ["cx", "pct"],
    baseConfidence: 0.86,
    recipeCandidate: false,
    neverRecipe: true,
    keywordsPositive: ["c/100", "c/50", "pacote"],
    keywordsNegative: [],
    aliases: [
      a("marmita", 0.86),
      a("tampa", 0.82),
      a("embalagem", 0.88),
      a("sacola", 0.85),
      a("copo descartavel", 0.87),
      a("copo descartável", 0.87),
      a("guardanapo", 0.85),
      a("canudo", 0.85),
    ],
  },
  {
    id: "mc-limpeza",
    canonicalName: "Produtos de limpeza e higiene",
    family: "Limpeza",
    subfamily: "Químicos / descartáveis",
    conceptType: "ITEM_OPERACIONAL",
    defaultUnit: "un",
    purchaseUnits: ["un", "cx", "galao"],
    baseConfidence: 0.87,
    recipeCandidate: false,
    neverRecipe: true,
    keywordsPositive: [],
    keywordsNegative: [],
    aliases: [
      a("detergente", 0.9),
      a("desinfetante", 0.88),
      a("agua sanitaria", 0.88),
      a("água sanitária", 0.88),
      a("papel toalha", 0.87),
      a("saco de lixo", 0.87),
      a("luva", 0.84),
      a("esponja", 0.84),
      a("alcool", 0.85),
      a("álcool", 0.85),
    ],
  },
  {
    id: "mc-equip-ti-coz",
    canonicalName: "Equipamentos, TI e MRO",
    family: "Equipamentos",
    subfamily: "Ativo / uso operacional",
    conceptType: "ATIVO_EQUIPAMENTO",
    defaultUnit: "un",
    purchaseUnits: ["un", "cx"],
    baseConfidence: 0.88,
    recipeCandidate: false,
    neverRecipe: true,
    keywordsPositive: ["led", "24", "27", "pol", "hp"],
    keywordsNegative: [],
    aliases: [
      a("monitor", 0.9),
      a("impressora", 0.9),
      a("computador", 0.9),
      a("nobreak", 0.88),
      a("tablet", 0.88),
      a("cabo", 0.85),
      a("balanca", 0.86),
      a("balança", 0.86),
      a("freezer", 0.86),
      a("geladeira", 0.86),
      a("forno", 0.86),
      a("fogao", 0.86),
      a("fogão", 0.86),
      a("cilindro", 0.84),
      a("co2", 0.85),
    ],
  },
  {
    id: "mc-receita-molho-casa",
    canonicalName: "Preparo / molho da casa (candidato a ficha)",
    family: "Molhos e bases",
    subfamily: "Casa / cardápio",
    conceptType: "RECEITA_CANDIDATE",
    defaultUnit: "un",
    purchaseUnits: ["un", "kg"],
    baseConfidence: 0.7,
    recipeCandidate: true,
    neverRecipe: false,
    keywordsPositive: ["casa", "especial"],
    keywordsNegative: [],
    aliases: [a("molho da casa", 0.78), a("moho da casa", 0.76, "SUPPLIER_VARIATION")],
  },
];
