import { canonicalProductName } from "@/lib/productImport/canonicalName";
import type { MasterRecipeDefinition } from "@/lib/masterRecipeCatalog/types";

function n(v: string): string {
  return canonicalProductName(v) || v.trim().toLowerCase();
}

export const MASTER_RECIPE_DEFINITIONS: MasterRecipeDefinition[] = [
  {
    id: "mr-drink-caipirinha-tradicional",
    canonicalName: "Caipirinha tradicional",
    normalizedName: n("Caipirinha tradicional"),
    recipeType: "DRINK_RECIPE",
    family: "Drinks",
    subcategory: "Caipirinhas",
    description: "Drink clássico com limão, açúcar e cachaça.",
    defaultYieldQuantity: 1,
    defaultYieldUnit: "un",
    defaultPortionQuantity: 1,
    defaultPortionUnit: "un",
    servingsCount: 1,
    prepTimeMinutes: 4,
    recipeCandidateScore: 0.95,
    status: "CURATED",
    origin: "SYSTEM_DEFAULT",
    curationStatus: "RECOMMENDED",
    isActive: true,
    aliases: ["caipirinha", "caipi tradicional"],
    components: [
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 0.12, unitCode: "kg", yieldFactor: 1, wasteFactor: 1.08, sortOrder: 1, optional: false },
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 0.02, unitCode: "kg", yieldFactor: 1, wasteFactor: 1, sortOrder: 2, optional: false },
      { componentKind: "MASTER_ITEM", masterItemId: "mc-beb-destilados", quantity: 0.06, unitCode: "l", yieldFactor: 1, wasteFactor: 1, sortOrder: 3, optional: false },
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 0.15, unitCode: "kg", yieldFactor: 1, wasteFactor: 1, sortOrder: 4, optional: true },
    ],
  },
  {
    id: "mr-drink-caipivodka",
    canonicalName: "Caipivodka",
    normalizedName: n("Caipivodka"),
    recipeType: "DRINK_RECIPE",
    family: "Drinks",
    subcategory: "Caipis",
    defaultYieldQuantity: 1,
    defaultYieldUnit: "un",
    defaultPortionQuantity: 1,
    defaultPortionUnit: "un",
    servingsCount: 1,
    prepTimeMinutes: 4,
    recipeCandidateScore: 0.93,
    status: "CURATED",
    origin: "SYSTEM_DEFAULT",
    curationStatus: "RECOMMENDED",
    isActive: true,
    aliases: ["caipi vodka", "caipivodka limao"],
    components: [
      { componentKind: "MASTER_RECIPE", masterRecipeId: "mr-drink-caipirinha-tradicional", quantity: 1, unitCode: "un", yieldFactor: 1, wasteFactor: 1, sortOrder: 1, optional: false },
      { componentKind: "MASTER_ITEM", masterItemId: "mc-beb-destilados", quantity: 0.06, unitCode: "l", yieldFactor: 1, wasteFactor: 1, sortOrder: 2, optional: false },
    ],
  },
  {
    id: "mr-drink-gin-tonica",
    canonicalName: "Gin tônica",
    normalizedName: n("Gin tônica"),
    recipeType: "DRINK_RECIPE",
    family: "Drinks",
    subcategory: "Highball",
    defaultYieldQuantity: 1,
    defaultYieldUnit: "un",
    defaultPortionQuantity: 1,
    defaultPortionUnit: "un",
    servingsCount: 1,
    prepTimeMinutes: 3,
    recipeCandidateScore: 0.94,
    status: "CURATED",
    origin: "SYSTEM_DEFAULT",
    curationStatus: "RECOMMENDED",
    isActive: true,
    aliases: ["gin tonica", "gin tônica"],
    components: [
      { componentKind: "MASTER_ITEM", masterItemId: "mc-beb-destilados", quantity: 0.05, unitCode: "l", yieldFactor: 1, wasteFactor: 1, sortOrder: 1, optional: false },
      { componentKind: "MASTER_ITEM", masterItemId: "mc-beb-na", quantity: 0.15, unitCode: "l", yieldFactor: 1, wasteFactor: 1, sortOrder: 2, optional: false },
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 0.04, unitCode: "kg", yieldFactor: 1, wasteFactor: 1.05, sortOrder: 3, optional: true },
    ],
  },
  {
    id: "mr-base-xarope-simples",
    canonicalName: "Xarope simples",
    normalizedName: n("Xarope simples"),
    recipeType: "SAUCE_BASE_RECIPE",
    family: "Bases de bar",
    subcategory: "Xaropes",
    defaultYieldQuantity: 1,
    defaultYieldUnit: "l",
    defaultPortionQuantity: 0.03,
    defaultPortionUnit: "l",
    servingsCount: 30,
    prepTimeMinutes: 10,
    recipeCandidateScore: 0.92,
    status: "CURATED",
    origin: "SYSTEM_DEFAULT",
    curationStatus: "RECOMMENDED",
    isActive: true,
    aliases: ["xarope", "calda simples"],
    components: [
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 0.5, unitCode: "kg", yieldFactor: 1, wasteFactor: 1, sortOrder: 1, optional: false },
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 0.5, unitCode: "l", yieldFactor: 1, wasteFactor: 1, sortOrder: 2, optional: false },
    ],
  },
  {
    id: "mr-prep-molho-casa",
    canonicalName: "Molho da casa",
    normalizedName: n("Molho da casa"),
    recipeType: "SUB_RECIPE",
    family: "Cozinha",
    subcategory: "Molhos",
    defaultYieldQuantity: 3,
    defaultYieldUnit: "kg",
    defaultPortionQuantity: 0.08,
    defaultPortionUnit: "kg",
    servingsCount: 35,
    prepTimeMinutes: 30,
    recipeCandidateScore: 0.89,
    status: "CURATED",
    origin: "SYSTEM_DEFAULT",
    curationStatus: "RECOMMENDED",
    isActive: true,
    aliases: ["molho especial", "molho casa"],
    components: [
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 1.5, unitCode: "kg", yieldFactor: 1, wasteFactor: 1.03, sortOrder: 1, optional: false },
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 0.12, unitCode: "kg", yieldFactor: 1, wasteFactor: 1, sortOrder: 2, optional: false },
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 0.03, unitCode: "kg", yieldFactor: 1, wasteFactor: 1, sortOrder: 3, optional: false },
    ],
  },
  {
    id: "mr-prep-arroz-base",
    canonicalName: "Arroz base",
    normalizedName: n("Arroz base"),
    recipeType: "PREP_RECIPE",
    family: "Cozinha",
    subcategory: "Pré-preparo",
    defaultYieldQuantity: 5,
    defaultYieldUnit: "kg",
    defaultPortionQuantity: 0.15,
    defaultPortionUnit: "kg",
    servingsCount: 30,
    prepTimeMinutes: 45,
    recipeCandidateScore: 0.88,
    status: "CURATED",
    origin: "SYSTEM_DEFAULT",
    curationStatus: "RECOMMENDED",
    isActive: true,
    aliases: ["arroz branco base", "arroz cozido base"],
    components: [
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 2, unitCode: "kg", yieldFactor: 2.5, wasteFactor: 1, sortOrder: 1, optional: false },
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 3.2, unitCode: "l", yieldFactor: 1, wasteFactor: 1, sortOrder: 2, optional: false },
    ],
  },
  {
    id: "mr-prep-massa-pizza",
    canonicalName: "Massa de pizza",
    normalizedName: n("Massa de pizza"),
    recipeType: "PREP_RECIPE",
    family: "Lanches e massas",
    subcategory: "Massas",
    defaultYieldQuantity: 20,
    defaultYieldUnit: "un",
    defaultPortionQuantity: 1,
    defaultPortionUnit: "un",
    servingsCount: 20,
    prepTimeMinutes: 120,
    recipeCandidateScore: 0.91,
    status: "CURATED",
    origin: "SYSTEM_DEFAULT",
    curationStatus: "RECOMMENDED",
    isActive: true,
    aliases: ["massa pizza", "disco pizza"],
    components: [
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 5, unitCode: "kg", yieldFactor: 1, wasteFactor: 1, sortOrder: 1, optional: false },
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 3.2, unitCode: "l", yieldFactor: 1, wasteFactor: 1, sortOrder: 2, optional: false },
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 0.12, unitCode: "kg", yieldFactor: 1, wasteFactor: 1, sortOrder: 3, optional: false },
    ],
  },
  {
    id: "mr-drink-mojito",
    canonicalName: "Mojito",
    normalizedName: n("Mojito"),
    recipeType: "DRINK_RECIPE",
    family: "Drinks",
    subcategory: "Muddled",
    description: "Rum, hortelã, limão, açúcar e soda.",
    defaultYieldQuantity: 1,
    defaultYieldUnit: "un",
    defaultPortionQuantity: 1,
    defaultPortionUnit: "un",
    servingsCount: 1,
    prepTimeMinutes: 5,
    recipeCandidateScore: 0.91,
    status: "CURATED",
    origin: "SYSTEM_DEFAULT",
    curationStatus: "RECOMMENDED",
    isActive: true,
    aliases: ["mojito clássico", "mojito tradicional"],
    components: [
      { componentKind: "MASTER_ITEM", masterItemId: "mc-beb-destilados", quantity: 0.05, unitCode: "l", yieldFactor: 1, wasteFactor: 1, sortOrder: 1, optional: false },
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 0.02, unitCode: "kg", yieldFactor: 1, wasteFactor: 1.05, sortOrder: 2, optional: false },
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 0.08, unitCode: "kg", yieldFactor: 1, wasteFactor: 1.08, sortOrder: 3, optional: false },
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 0.03, unitCode: "kg", yieldFactor: 1, wasteFactor: 1, sortOrder: 4, optional: false },
      { componentKind: "MASTER_ITEM", masterItemId: "mc-beb-na", quantity: 0.12, unitCode: "l", yieldFactor: 1, wasteFactor: 1, sortOrder: 5, optional: false },
    ],
  },
  {
    id: "mr-drink-moscow-mule",
    canonicalName: "Moscow Mule",
    normalizedName: n("Moscow Mule"),
    recipeType: "DRINK_RECIPE",
    family: "Drinks",
    subcategory: "Highball",
    description: "Vodka, ginger beer e limão.",
    defaultYieldQuantity: 1,
    defaultYieldUnit: "un",
    defaultPortionQuantity: 1,
    defaultPortionUnit: "un",
    servingsCount: 1,
    prepTimeMinutes: 4,
    recipeCandidateScore: 0.9,
    status: "CURATED",
    origin: "SYSTEM_DEFAULT",
    curationStatus: "RECOMMENDED",
    isActive: true,
    aliases: ["moscow", "mule"],
    components: [
      { componentKind: "MASTER_ITEM", masterItemId: "mc-beb-destilados", quantity: 0.06, unitCode: "l", yieldFactor: 1, wasteFactor: 1, sortOrder: 1, optional: false },
      { componentKind: "MASTER_ITEM", masterItemId: "mc-beb-na", quantity: 0.15, unitCode: "l", yieldFactor: 1, wasteFactor: 1, sortOrder: 2, optional: false },
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 0.04, unitCode: "kg", yieldFactor: 1, wasteFactor: 1.05, sortOrder: 3, optional: true },
    ],
  },
  {
    id: "mr-prep-feijao-base",
    canonicalName: "Feijão cozido base",
    normalizedName: n("Feijão cozido base"),
    recipeType: "PREP_RECIPE",
    family: "Cozinha",
    subcategory: "Grãos",
    description: "Feijão pré-cozido para porções e montagem.",
    defaultYieldQuantity: 5,
    defaultYieldUnit: "kg",
    defaultPortionQuantity: 0.15,
    defaultPortionUnit: "kg",
    servingsCount: 30,
    prepTimeMinutes: 120,
    recipeCandidateScore: 0.87,
    status: "CURATED",
    origin: "SYSTEM_DEFAULT",
    curationStatus: "RECOMMENDED",
    isActive: true,
    aliases: ["feijão base", "feijao cozido"],
    components: [
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 2, unitCode: "kg", yieldFactor: 1, wasteFactor: 1.02, sortOrder: 1, optional: false },
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 0.2, unitCode: "kg", yieldFactor: 1, wasteFactor: 1, sortOrder: 2, optional: false },
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 0.05, unitCode: "kg", yieldFactor: 1, wasteFactor: 1, sortOrder: 3, optional: false },
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 0.02, unitCode: "kg", yieldFactor: 1, wasteFactor: 1, sortOrder: 4, optional: false },
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 6, unitCode: "l", yieldFactor: 1, wasteFactor: 1, sortOrder: 5, optional: false },
    ],
  },
  {
    id: "mr-prep-maionese-casa",
    canonicalName: "Maionese da casa",
    normalizedName: n("Maionese da casa"),
    recipeType: "PREP_RECIPE",
    family: "Cozinha",
    subcategory: "Molhos",
    description: "Emulsão básica de óleo e limão.",
    defaultYieldQuantity: 1,
    defaultYieldUnit: "kg",
    defaultPortionQuantity: 0.04,
    defaultPortionUnit: "kg",
    servingsCount: 24,
    prepTimeMinutes: 20,
    recipeCandidateScore: 0.88,
    status: "CURATED",
    origin: "SYSTEM_DEFAULT",
    curationStatus: "RECOMMENDED",
    isActive: true,
    aliases: ["maionese caseira"],
    components: [
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 0.65, unitCode: "l", yieldFactor: 1, wasteFactor: 1, sortOrder: 1, optional: false },
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 0.15, unitCode: "kg", yieldFactor: 1, wasteFactor: 1.03, sortOrder: 2, optional: false },
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 0.04, unitCode: "kg", yieldFactor: 1, wasteFactor: 1.02, sortOrder: 3, optional: false },
      { componentKind: "MASTER_ITEM", masterItemId: "mc-ins-horti-mercado", quantity: 0.01, unitCode: "kg", yieldFactor: 1, wasteFactor: 1, sortOrder: 4, optional: true },
    ],
  },
];

export function masterRecipeDefinitionByExternalKey(externalKey: string): MasterRecipeDefinition | undefined {
  return MASTER_RECIPE_DEFINITIONS.find((d) => d.id === externalKey);
}
