-- Exemplo: chamar `focus-sync-nfe-recebidas` uma vez por empresa (evita timeout / WORKER_RESOURCE_LIMIT).
-- Ajuste URL, chaves e secret. Requer extensão `pg_net` (ou equivalente) e gestão segura de secrets.
--
-- Autenticação: header `Authorization: Bearer <FOCUS_NFE_RECEBIDAS_CRON_SECRET>` (obrigatório).
-- Opcional no body: `company_id` (UUID) para processar só essa unidade (recomendado).
-- Opcional: `phase`: "auto" (padrão), "list" (só cabeçalhos → fila), "download" (só XML a partir da fila).
--
-- Variáveis de ambiente na Edge (orçamentos, ver comentário no index da função):
--   FOCUS_SYNC_MAX_COMPANIES_PER_RUN (default 1)
--   FOCUS_SYNC_MAX_LIST_PAGES (default 8)
--   FOCUS_SYNC_LIST_PAGE_SIZE (default 25; query `limite` na listagem)
--   FOCUS_SYNC_MAX_XML_DOWNLOADS_PER_RUN (default 20)
--   FOCUS_SYNC_SOFT_BUDGET_MS (0 = desligado)
--   FOCUS_SYNC_LEASE_MINUTES (default 30)
--   FOCUS_SYNC_MAX_CHAIN_DEPTH (default 2)
--
-- Exemplo com net.http_post (sintaxe pode variar consoante a versão do pg_net):
--
-- SELECT net.http_post(
--   url := 'https://<PROJECT_REF>.supabase.co/functions/v1/focus-sync-nfe-recebidas',
--   headers := jsonb_build_object(
--     'Content-Type', 'application/json',
--     'Authorization', 'Bearer ' || '<FOCUS_NFE_RECEBIDAS_CRON_SECRET>',
--     'apikey', '<SUPABASE_ANON_KEY>'
--   ),
--   body := jsonb_build_object(
--     'company_id', '<COMPANY_UUID>'
--   )::text
-- );
--
-- Cron “várias unidades”: omitir `company_id` no body; a função processa no máximo
-- FOCUS_SYNC_MAX_COMPANIES_PER_RUN unidades elegíveis por POST (default 1).
