-- Secrets para crons NF-e (pg_cron → net.http_post).
-- Executar no SQL Editor (produção) ou após `supabase db reset` em dev, com valores reais.
--
-- Nomes **exatos** (coluna `name` em vault.secrets / visão decrypted_secrets):
--   focus_interpret_cron_supabase_url
--   focus_interpret_cron_anon_key
--   focus_interpret_cron_bearer_secret   (= FOCUS_NFE_RECEBIDAS_CRON_SECRET nas Edge Functions)
--
-- Jobs pg_cron (após migrations):
--   focus_get_sync_nfe_recebidas          — listagem Focus (rodízio)
--   focus_get_sync_nfe_onboarding_retry   — retry SEFAZ no onboarding
--
-- A fila focus_get_sync_nfe_interpret_jobs / cron interpret_dispatch foi removida.

-- Exemplo (API Dashboard Vault ou extensão vault — sintaxe pode variar):
-- select vault.create_secret('https://SEU_REF.supabase.co', 'focus_interpret_cron_supabase_url');
-- select vault.create_secret('SUA_ANON_KEY', 'focus_interpret_cron_anon_key');
-- select vault.create_secret('MESMO_SECRET_DO_CRON_FOCUS', 'focus_interpret_cron_bearer_secret');
